version: '3'

services:
  html-parser:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/usr/src/app
    container_name: html-parser-container
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev